import type { InventoryItem } from "./types";

// ─── Mock Inventory ────────────────────────────────────────────────────────────
// 20 active + 1 sold. Distribution: 5 Critical · 5 High · 5 Medium · 5 Low
//
// Dead Inventory Score breakdown:
//   days_listed: ≤30→0  ≤60→15  ≤90→35  ≤180→50  else→60  (max 60)
//   missing specifics: +15
//   image_count=1: +12  | 2–3: +5
//   title_keyword_strength: <40→+13  <60→+7  <75→+3
//   Risk: Critical ≥75 · High ≥50 · Medium ≥30 · Low <30
//
// Engagement metrics reflect realistic platform behavior:
//   Critical items: high impressions, low watchers (seen but not converting)
//   High risk: moderate views, some watchers (slight interest, no conversion)
//   Medium: lower views (still active, partial visibility)
//   Low: fresh, low totals but healthy watcher-to-view ratio
// ─────────────────────────────────────────────────────────────────────────────

const NOW = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const MOCK_ITEMS: InventoryItem[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // CRITICAL — Score ≥75. Death pile. Functionally invisible.
  // ═══════════════════════════════════════════════════════════════════════════

  {
    // Score: 60 (312d) + 15 (no spec) + 5 (2 photos) + 3 (title 72, ≥60<75) = 83
    // Action: relist_now — 312d < 365d, price $45 > $15, worth fresh listing
    // Engagement: high impressions (been seen 300+ times), zero new interest
    id: "1",
    user_id: "demo",
    title: "Vintage Levi's 501 Jeans 34x32 Distressed Worn Fade 90s Grunge",
    platform: "eBay",
    price: 45.00,
    original_price: 55.00,
    cost_basis: 12.00,
    days_listed: 312,
    date_listed: daysAgo(312),
    category: "Vintage Clothing",
    item_specifics_complete: false,
    image_count: 2,
    title_keyword_strength: 72,
    has_promoted_listing: false,
    shipping_type: "calculated",
    shipping_cost: 6.50,
    views: 347,
    watchers: 1,
    impressions: 1240,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(312),
    updated_at: daysAgo(45),
  },
  {
    // Score: 60 (245d) + 15 (no spec) + 5 (3 photos) + 0 (title 80, ≥75) = 80
    // Action: relist_now — high value, 245d, worth full relist effort
    // Engagement: people find it, no one's buying at this price without fresh listing
    id: "2",
    user_id: "demo",
    title: "Air Jordan 1 Retro High OG Chicago 2015 Nike Size 11 DS",
    platform: "eBay",
    price: 285.00,
    original_price: 320.00,
    cost_basis: 180.00,
    days_listed: 245,
    date_listed: daysAgo(245),
    category: "Sneakers",
    item_specifics_complete: false,
    image_count: 3,
    title_keyword_strength: 80,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 892,
    watchers: 4,
    impressions: 3100,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(245),
    updated_at: daysAgo(60),
  },
  {
    // Score: 60 (198d) + 15 (no spec) + 12 (1 photo) + 7 (title 55, ≥40<60) = 94
    // Action: relist_now — single photo is killing CTR, relist with 8+ photos
    id: "3",
    user_id: "demo",
    title: "Nintendo 64 Console Bundle N64 With 2 Controllers All Cords",
    platform: "eBay",
    price: 120.00,
    original_price: 150.00,
    cost_basis: 35.00,
    days_listed: 198,
    date_listed: daysAgo(198),
    category: "Electronics",
    item_specifics_complete: false,
    image_count: 1,
    title_keyword_strength: 55,
    has_promoted_listing: false,
    shipping_type: "calculated",
    shipping_cost: 14.00,
    views: 223,
    watchers: 0,
    impressions: 780,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(198),
    updated_at: daysAgo(90),
  },
  {
    // Score: 60 (421d) + 15 (no spec) + 12 (1 photo) + 3 (title 68, ≥60<75) = 90
    // Action: liquidate — 421d > 365d, carrying cost exceeds recovery potential
    id: "4",
    user_id: "demo",
    title: "Ralph Lauren Polo Bear Knit Sweater Large Vintage Rare 1990s",
    platform: "eBay",
    price: 95.00,
    original_price: 115.00,
    cost_basis: 28.00,
    days_listed: 421,
    date_listed: daysAgo(421),
    category: "Vintage Clothing",
    item_specifics_complete: false,
    image_count: 1,
    title_keyword_strength: 68,
    has_promoted_listing: false,
    shipping_type: "calculated",
    shipping_cost: 5.50,
    views: 510,
    watchers: 2,
    impressions: 1870,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(421),
    updated_at: daysAgo(120),
  },
  {
    // Score: 60 (380d) + 15 (no spec) + 12 (1 photo) + 7 (title 40, <60) = 94
    // Action: bundle — price $8 < $15, not worth solo relist, combine into lot
    id: "5",
    user_id: "demo",
    title: "Funko Pop Lot 12 Mixed Marvel DC Hot Topic Exclusives",
    platform: "eBay",
    price: 8.00,
    original_price: 12.00,
    cost_basis: 3.00,
    days_listed: 380,
    date_listed: daysAgo(380),
    category: "Collectibles",
    item_specifics_complete: false,
    image_count: 1,
    title_keyword_strength: 40,
    has_promoted_listing: false,
    shipping_type: "calculated",
    views: 89,
    watchers: 0,
    impressions: 430,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(380),
    updated_at: daysAgo(200),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HIGH — Score 50–74. Algorithm has deprioritized these. Act this week.
  // ═══════════════════════════════════════════════════════════════════════════

  {
    // Score: 50 (142d) + 0 (complete) + 0 (5 photos) + 0 (title 88, ≥75) = 50
    // Action: strategic_markdown — listing quality is fine, price is the lever
    // 4 watchers = active interest; a 15–20% drop will trigger notifications
    id: "6",
    user_id: "demo",
    title: "Supreme Box Logo Hoodie FW18 Black Large Bogo Authentic",
    platform: "eBay",
    price: 340.00,
    original_price: 375.00,
    cost_basis: 220.00,
    days_listed: 142,
    date_listed: daysAgo(142),
    category: "Streetwear",
    item_specifics_complete: true,
    image_count: 5,
    title_keyword_strength: 88,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 445,
    watchers: 4,
    impressions: 1340,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(142),
    updated_at: daysAgo(30),
  },
  {
    // Score: 50 (130d) + 0 (complete) + 0 (4 photos) + 3 (title 65, ≥60<75) = 53
    // Action: strategic_markdown — 4-month PS2, decent listing, price stagnation
    id: "7",
    user_id: "demo",
    title: "Sony PlayStation 2 PS2 Slim Silver Console SCPH-77001 Tested Works",
    platform: "eBay",
    price: 89.00,
    original_price: 99.00,
    cost_basis: 22.00,
    days_listed: 130,
    date_listed: daysAgo(130),
    category: "Electronics",
    item_specifics_complete: true,
    image_count: 4,
    title_keyword_strength: 65,
    has_promoted_listing: false,
    shipping_type: "calculated",
    shipping_cost: 12.00,
    views: 312,
    watchers: 2,
    impressions: 980,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(130),
    updated_at: daysAgo(20),
  },
  {
    // Score: 50 (112d) + 15 (no spec) + 5 (2 photos) + 3 (title 70, ≥60<75) = 73
    // Action: optimize_specifics — biggest quick win; Depop buyers use filters too
    id: "8",
    user_id: "demo",
    title: "Carhartt WIP Detroit Jacket Brown Canvas Lined Blanket Medium",
    platform: "Depop",
    price: 78.00,
    original_price: 95.00,
    cost_basis: 35.00,
    days_listed: 112,
    date_listed: daysAgo(112),
    category: "Workwear",
    item_specifics_complete: false,
    image_count: 2,
    title_keyword_strength: 70,
    has_promoted_listing: false,
    shipping_type: "flat",
    shipping_cost: 7.00,
    views: 198,
    watchers: 1,
    impressions: 560,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(112),
    updated_at: daysAgo(14),
  },
  {
    // Score: 35 (98d) + 15 (no spec) + 0 (4 photos) + 0 (title 82, ≥75) = 50
    // Action: optimize_specifics — approaching 90-day cliff, missing specifics
    // is the fastest fix before it falls off completely
    id: "9",
    user_id: "demo",
    title: "Pyrex Vision Hoodie Red 2012 Virgil Abloh Off-White Size M",
    platform: "eBay",
    price: 450.00,
    original_price: 480.00,
    cost_basis: 280.00,
    days_listed: 98,
    date_listed: daysAgo(98),
    category: "Streetwear",
    item_specifics_complete: false,
    image_count: 4,
    title_keyword_strength: 82,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 623,
    watchers: 6,
    impressions: 1890,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(98),
    updated_at: daysAgo(7),
  },
  {
    // Score: 50 (120d) + 0 (complete) + 5 (3 photos) + 7 (title 58, ≥40<60) = 62
    // Action: strategic_markdown — 4 months on Poshmark with no offers
    // Drop $10+ to trigger liker notifications; Poshmark price-drop algorithm
    id: "10",
    user_id: "demo",
    title: "Coach Leather Shoulder Bag Brown Vintage Y2K Legacy Purse",
    platform: "Poshmark",
    price: 55.00,
    original_price: 65.00,
    cost_basis: 18.00,
    days_listed: 120,
    date_listed: daysAgo(120),
    category: "Handbags",
    item_specifics_complete: true,
    image_count: 3,
    title_keyword_strength: 58,
    has_promoted_listing: false,
    shipping_type: "flat",
    shipping_cost: 7.97,
    views: 234,
    watchers: 8,
    impressions: 670,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(120),
    updated_at: daysAgo(35),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MEDIUM — Score 30–49. Showing age. Targeted fixes will unlock these.
  // ═══════════════════════════════════════════════════════════════════════════

  {
    // Score: 35 (67d) + 0 (complete) + 0 (6 photos) + 0 (title 85, ≥75) = 35
    // Action: move_platform — fully optimized, not moving → wrong audience
    // Nike SBs move faster on StockX / GOAT than eBay for this style
    id: "11",
    user_id: "demo",
    title: "Nike SB Dunk Low Pro Hemp Natural 2021 Size 10.5 Deadstock",
    platform: "eBay",
    price: 165.00,
    original_price: 165.00,
    cost_basis: 110.00,
    days_listed: 67,
    date_listed: daysAgo(67),
    category: "Sneakers",
    item_specifics_complete: true,
    image_count: 6,
    title_keyword_strength: 85,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 188,
    watchers: 2,
    impressions: 560,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(67),
    updated_at: daysAgo(10),
  },
  {
    // Score: 35 (74d) + 0 (complete) + 0 (4 photos) + 0 (title 78, ≥75) = 35
    // Action: strategic_markdown — quality listing, 74d sitting → price drop triggers activity
    id: "12",
    user_id: "demo",
    title: "Polaroid SX-70 Land Camera Vintage Film Tested Working Fully",
    platform: "eBay",
    price: 75.00,
    original_price: 85.00,
    cost_basis: 20.00,
    days_listed: 74,
    date_listed: daysAgo(74),
    category: "Cameras",
    item_specifics_complete: true,
    image_count: 4,
    title_keyword_strength: 78,
    has_promoted_listing: false,
    shipping_type: "calculated",
    shipping_cost: 8.00,
    views: 156,
    watchers: 3,
    impressions: 490,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(74),
    updated_at: daysAgo(15),
  },
  {
    // Score: 35 (68d) + 0 (complete) + 5 (2 photos) + 3 (title 64, ≥60<75) = 43
    // Action: add_photos — 2 photos is below the 4-photo CTR floor;
    // Mercari is visual, more photos = more trust
    id: "13",
    user_id: "demo",
    title: "Tommy Hilfiger Flag Crewneck Sweatshirt Size XL 90s Vintage",
    platform: "Mercari",
    price: 32.00,
    original_price: 38.00,
    cost_basis: 8.00,
    days_listed: 68,
    date_listed: daysAgo(68),
    category: "Vintage Clothing",
    item_specifics_complete: true,
    image_count: 2,
    title_keyword_strength: 64,
    has_promoted_listing: false,
    shipping_type: "flat",
    shipping_cost: 5.00,
    views: 145,
    watchers: 1,
    impressions: 420,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(68),
    updated_at: daysAgo(8),
  },
  {
    // Score: 35 (83d) + 0 (complete) + 5 (3 photos) + 0 (title 90, ≥75) = 40
    // Action: strategic_markdown — 83d with good listing, niche collectible,
    // price-sensitive market, a 15% drop changes the buyer calculation
    id: "14",
    user_id: "demo",
    title: "BE@RBRICK 400% Medicom Toy KAWS Companion Figure 2020 NIB",
    platform: "eBay",
    price: 210.00,
    original_price: 230.00,
    cost_basis: 140.00,
    days_listed: 83,
    date_listed: daysAgo(83),
    category: "Collectibles",
    item_specifics_complete: true,
    image_count: 3,
    title_keyword_strength: 90,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 276,
    watchers: 5,
    impressions: 820,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(83),
    updated_at: daysAgo(12),
  },
  {
    // Score: 35 (62d) + 0 (complete) + 0 (7 photos) + 0 (title 92, ≥75) = 35
    // Action: move_platform — listing optimized, Yeezy market moved to GOAT/StockX,
    // eBay is crowded with fakes → authentic pairs move faster with authentication
    id: "15",
    user_id: "demo",
    title: "Adidas Yeezy Boost 350 V2 Zebra CP9654 Size 9 DS OG All",
    platform: "StockX",
    price: 225.00,
    original_price: 225.00,
    cost_basis: 160.00,
    days_listed: 62,
    date_listed: daysAgo(62),
    category: "Sneakers",
    item_specifics_complete: true,
    image_count: 7,
    title_keyword_strength: 92,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 310,
    watchers: 0,
    impressions: 890,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(62),
    updated_at: daysAgo(5),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LOW — Score <30. Fresh, well-listed. Hold and monitor.
  // ═══════════════════════════════════════════════════════════════════════════

  {
    // Score: 0 (12d) + 0 + 0 (5 photos) + 0 (title 80) = 0
    id: "16",
    user_id: "demo",
    title: "Carhartt Beanie Watch Hat Black OG Acrylic Knit Unisex USA",
    platform: "eBay",
    price: 18.00,
    original_price: 18.00,
    cost_basis: 4.00,
    days_listed: 12,
    date_listed: daysAgo(12),
    category: "Accessories",
    item_specifics_complete: true,
    image_count: 5,
    title_keyword_strength: 80,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 42,
    watchers: 2,
    impressions: 180,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(12),
    updated_at: daysAgo(2),
  },
  {
    // Score: 0 (8d) = 0
    id: "17",
    user_id: "demo",
    title: "Stussy 8 Ball Fleece Crewneck Sweatshirt Black Large 2023 NWT",
    platform: "Depop",
    price: 85.00,
    original_price: 85.00,
    cost_basis: 45.00,
    days_listed: 8,
    date_listed: daysAgo(8),
    category: "Streetwear",
    item_specifics_complete: true,
    image_count: 8,
    title_keyword_strength: 88,
    has_promoted_listing: false,
    shipping_type: "flat",
    shipping_cost: 6.00,
    views: 67,
    watchers: 4,
    impressions: 310,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
  },
  {
    // Score: 0 (22d) = 0
    id: "18",
    user_id: "demo",
    title: "Vintage Marlboro Racing Jacket Medium USA Made 1995 Philip Morris",
    platform: "eBay",
    price: 125.00,
    original_price: 125.00,
    cost_basis: 55.00,
    days_listed: 22,
    date_listed: daysAgo(22),
    category: "Vintage Clothing",
    item_specifics_complete: true,
    image_count: 9,
    title_keyword_strength: 91,
    has_promoted_listing: true,
    shipping_type: "calculated",
    shipping_cost: 6.00,
    views: 198,
    watchers: 7,
    impressions: 740,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(22),
    updated_at: daysAgo(3),
  },
  {
    // Score: 0 (5d) = 0
    id: "19",
    user_id: "demo",
    title: "New Balance 990v3 Made in USA Grey M990GL3 Size 11.5 NWT",
    platform: "eBay",
    price: 195.00,
    original_price: 195.00,
    cost_basis: 130.00,
    days_listed: 5,
    date_listed: daysAgo(5),
    category: "Sneakers",
    item_specifics_complete: true,
    image_count: 10,
    title_keyword_strength: 95,
    has_promoted_listing: true,
    shipping_type: "free",
    views: 88,
    watchers: 3,
    impressions: 390,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    // Score: 0 (18d) = 0
    id: "20",
    user_id: "demo",
    title: "Pokemon Base Set Charizard Holo 4/102 PSA 7 NM Graded Slab",
    platform: "eBay",
    price: 380.00,
    original_price: 380.00,
    cost_basis: 260.00,
    days_listed: 18,
    date_listed: daysAgo(18),
    category: "Collectibles",
    item_specifics_complete: true,
    image_count: 6,
    title_keyword_strength: 96,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 312,
    watchers: 9,
    impressions: 1050,
    status: "active",
    image_url: undefined,
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SOLD — Historical reference. Excluded from active calculations.
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "21",
    user_id: "demo",
    title: "Vintage Starter Satin Snap Jacket Chicago Bulls XL 90s NBA",
    platform: "eBay",
    price: 145.00,
    original_price: 145.00,
    cost_basis: 60.00,
    days_listed: 14,
    date_listed: daysAgo(45),
    category: "Vintage Clothing",
    item_specifics_complete: true,
    image_count: 7,
    title_keyword_strength: 87,
    has_promoted_listing: false,
    shipping_type: "free",
    views: 223,
    watchers: 12,
    impressions: 890,
    status: "sold",
    image_url: undefined,
    created_at: daysAgo(45),
    updated_at: daysAgo(31),
  },
];

export const DEMO_USER = {
  id: "demo",
  email: "seller@rejectedeconomy.com",
};
